name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build
        run: |
          echo "DO NOTHING"
